### ISSUE TITLE
UI層の構造を検討する

### ISSUE THREAD

**Issue by Yatsuku** [Yatsuku/ETR2017-SLP-KGW#2]
今回はSmart UIを作らない方向で進めているが、内容が複雑になりそうな場合は
Viewとロジックを結びつけるかもしれない。

**Comment by Yatsuku** [comment]
他のレイヤーとの繋がりを検討している。

**Comment by Yatsuku** [comment]
@shiotomo の担当箇所。
レイヤーの設計、実装は支援する予定。

**Comment by Yatsuku** [comment]
article, presenter, controllerの3層で設計。

**Comment by MaxMEllon** [comment]
チケット名が不適切じゃない？
作業しない というタイトルの作業項目が作業一覧にあるのは違和感．
このタスクゴールはなんだろう

**Comment by Yatsuku** [comment]
questionのラベルが貼ってあるチケットは「~を考察する。」というタイトルにしました。
